import DS from 'ember-data';

export default DS.Model.extend({
  dwelling_type: DS.attr('string'),
  year_built: DS.attr('number'),
  square_footage: DS.attr('number'),
  number_of_adults: DS.attr('number'),
  number_of_children: DS.attr('number'),
  home_business: DS.attr('boolean'),
  ownership: DS.attr('boolean'),
  hvac_heating_config: DS.attr('string'),
  hvac_cooling_config: DS.attr('string'),
  programmable_tstat: DS.attr('boolean'),
  tstat_programmed: DS.attr('boolean'),
  water_heater_type: DS.attr('string'),
  pool_pump: DS.attr('boolean'),
  hot_tub: DS.attr('boolean'),
  pool_heat_type: DS.attr('string'),
  avg_cooling_setpoint: DS.attr('number'),
  avg_heating_setpoint: DS.attr('number'),
  x_refrigerator: DS.attr('boolean'),
  x_freezer: DS.attr('boolean'),
  x_dish_washer: DS.attr('boolean'),
  oven: DS.attr('boolean'),
  cooktop: DS.attr('boolean'),
  x_washing_machine: DS.attr('boolean'),
  clothes_dryer: DS.attr('boolean'),
  x_num_tvs: DS.attr('number'),
  x_tv_estar: DS.attr('number'),
  x_tv_hours: DS.attr('number'),
  num_laptops: DS.attr('number'),
  solar_electric: DS.attr('boolean'),
  num_incandescent: DS.attr('number'),
  hours_incandescent: DS.attr('number'),
  num_cfl: DS.attr('number'),
  hours_cfl: DS.attr('number'),
  num_led: DS.attr('number'),
  hours_led: DS.attr('number'),
  num_flourescent: DS.attr('number'),
  hours_flourescent: DS.attr('number'),
  num_halogen: DS.attr('number'),
  hours_halogen: DS.attr('number')
});
